import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ResNav from "./components/ResNav";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <ResNav/>
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}